spring.application.name=ms-usuarios
server.port=8082

# Base de datos MySQL (XAMPP)
# Crea la BD "ms_usuarios" en phpMyAdmin antes de correr el proyecto.
# Las tablas se crean automaticamente con ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3307/ms_usuarios
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - DEBE SER EL MISMO SECRET QUE EN ms-login
# Asi este microservicio puede leer los tokens generados por ms-login
jwt.secret=c2VjcmV0b011eUZ1ZXJ0ZVBhcmFDYXJkTGlua1Byb3llY3RvRHVvYzIwMjY=
jwt.expiration=86400000

# URL del microservicio de login (por si necesitas consultarlo en el futuro)
ms.login.url=http://localhost:8081